name: GO

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu \
            libbtrfs-dev libgpgme-dev libdevmapper-dev \
            qemu-user-static binfmt-support

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: build --snapshot --clean  --timeout=1h
      - name: Copy file
        run: |
          cp dist/sreg_linux_amd64_v1/sreg  sreg
          chmod a+x sreg
          ./sreg version
